### ISSUE TITLE
Issue with moodle 4.0.1

### ISSUE THREAD

**Issue by moumitahalder** [dualcube/moodle-tinymce_virtualkeyboard#4]
editor_plugin.js:1 Uncaught TypeError: Cannot read properties of null (reading 'click')
at Editor. (editor_plugin.js:1:217)
at Editor.execCommand (tiny_mce.js:1:176353)
at i.onclick (tiny_mce.js:1:199433)
at HTMLAnchorElement. (tiny_mce.js:1:139791)
at j (tiny_mce.js:1:58627)
at HTMLAnchorElement.y (tiny_mce.js:1:58785)

**Comment by moumitahalder** [comment]
![image](https://github.com/dualcube/moodle-tinymce_virtualkeyboard/assets/28754174/640d2859-d691-4331-99dc-73b256ef4c61)

**Comment by Bhanuka94** [comment]
Hi, any progress with this issue resolving?

**Comment by moumitahalder** [comment]
Hi @Bhanuka94 , we are not able to recreate the issue from our end.
Can you please contact us over here https://dualcube.com/contact-us/, so we can assist you accordingly.
